version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
  db_test:
    container_name: pg_container_for_test
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "6000:6000"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"